
version: '3.8'

services:
  app:
    container_name: lafayette_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5044:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
